import { Category } from '@/types';

export interface SeedItem {
  category: Category;
  name: string;
  min_qty: string;
  stock: number;
  office_stock?: number;
  expiry_date?: string;
}

export const SEED_DATA: SeedItem[] = [
  // 파우더
  { category: '파우더', name: '밀크베이스', min_qty: '2', stock: 1 },
  { category: '파우더', name: '프리미엄베이스', min_qty: '1', stock: 1 },
  { category: '파우더', name: '밀크쉐이크', min_qty: '2', stock: 2 },
  { category: '파우더', name: '프로틴', min_qty: '1', stock: 1 },
  { category: '파우더', name: '말차', min_qty: '2', stock: 1 },
  { category: '파우더', name: '흑임자', min_qty: '1', stock: 0 },
  { category: '파우더', name: '17곡', min_qty: '1', stock: 1 },
  { category: '파우더', name: '밤(시즌 한정)', min_qty: '2', stock: 1 },
  { category: '파우더', name: '블루베리', min_qty: '1', stock: 1 },
  { category: '파우더', name: '바나나', min_qty: '2', stock: 1 },
  { category: '파우더', name: '타로', min_qty: '2', stock: 2, office_stock: 3 },
  { category: '파우더', name: '코코넛', min_qty: '1', stock: 1 },
  { category: '파우더', name: '요거트', min_qty: '2', stock: 2 },
  { category: '파우더', name: '바닐라라떼', min_qty: '2', stock: 3 },
  { category: '파우더', name: '바닐라향', min_qty: '2', stock: 2 },
  { category: '파우더', name: '초코', min_qty: '2', stock: 2 },
  { category: '파우더', name: '자바칩', min_qty: '2', stock: 2 },
  { category: '파우더', name: '코코아', min_qty: '1', stock: 0 },
  { category: '파우더', name: '가벼운 요거트', min_qty: '1', stock: 1 },
  { category: '파우더', name: '가벼운 초코', min_qty: '1', stock: 1 },
  { category: '파우더', name: '가벼운 타로', min_qty: '1', stock: 1 },
  { category: '파우더', name: '비타민', min_qty: '1', stock: 0 },
  // 시럽
  { category: '시럽', name: '딸기', min_qty: '4', stock: 4, office_stock: 3 },
  { category: '시럽', name: '망고', min_qty: '3', stock: 4 },
  { category: '시럽', name: '청포도', min_qty: '4', stock: 6 },
  { category: '시럽', name: '유자', min_qty: '3', stock: 2 },
  { category: '시럽', name: '깔라만시', min_qty: '절반', stock: 0 },
  { category: '시럽', name: '뱅쇼', min_qty: '1', stock: 1 },
  { category: '시럽', name: '고구마(시즌)', min_qty: '2', stock: 1 },
  { category: '시럽', name: '라이트 딸기', min_qty: '1', stock: 1 },
  { category: '시럽', name: '라이트 망고', min_qty: '1', stock: 0 },
  { category: '시럽', name: '라이트 청포도', min_qty: '1', stock: 1 },
  { category: '시럽', name: '홍차', min_qty: '2', stock: 6, office_stock: 3 },
  { category: '시럽', name: '흑당', min_qty: '1', stock: 1 },
  { category: '시럽', name: '아이스티', min_qty: '3', stock: 4, office_stock: 6 },
  { category: '시럽', name: '제로 아이스티', min_qty: '1', stock: 2, office_stock: 6 },
  { category: '시럽', name: '카페시럽', min_qty: '4', stock: 1 },
  { category: '시럽', name: '제로 카페시럽', min_qty: '3', stock: 5 },
  { category: '시럽', name: '초코소스', min_qty: '1', stock: 3 },
  { category: '시럽', name: '제로 바닐라', min_qty: '절반', stock: 0 },
  { category: '시럽', name: '제로 카라멜', min_qty: '절반', stock: 0 },
  { category: '시럽', name: '제로 허니자몽', min_qty: '1', stock: 1 },
  { category: '시럽', name: '제로 청사과', min_qty: '2', stock: 0 },
  { category: '시럽', name: '제로 레몬', min_qty: '3', stock: 0 },
  { category: '시럽', name: '카테킨', min_qty: '1', stock: 1 },
  { category: '시럽', name: '애사비', min_qty: '1', stock: 0 },
  { category: '시럽', name: '헛개수', min_qty: '1', stock: 1 },
  // 이외품목
  { category: '이외품목', name: '콜드브루', min_qty: '3', stock: 1 },
  { category: '이외품목', name: '캐모마일', min_qty: '1', stock: 1 },
  { category: '이외품목', name: '히비스커스', min_qty: '1', stock: 0 },
  { category: '이외품목', name: '블랙퍼스트', min_qty: '1', stock: 1 },
  { category: '이외품목', name: '나타드코코', min_qty: '4', stock: 12 },
  { category: '이외품목', name: '곤약펄', min_qty: '1', stock: 1 },
  { category: '이외품목', name: '타피오카펄', min_qty: '3', stock: 3 },
  { category: '이외품목', name: '시나몬스틱', min_qty: '1', stock: 0 },
  { category: '이외품목', name: '다크블로썸', min_qty: '절반', stock: 1 },
  { category: '이외품목', name: '볶음 코코넛', min_qty: '절반', stock: 0 },
  { category: '이외품목', name: '냉딸', min_qty: '4', stock: 2 },
  { category: '이외품목', name: '냉망', min_qty: '2', stock: 4 },
  { category: '이외품목', name: '냉블', min_qty: '1', stock: 2 },
  { category: '이외품목', name: '연유', min_qty: '4개', stock: 15 },
  { category: '이외품목', name: '휘핑', min_qty: '3개', stock: 2 },
  { category: '이외품목', name: '벤티컵', min_qty: '80%', stock: 0 },
  { category: '이외품목', name: '대용량컵', min_qty: '절반', stock: 0 },
  { category: '이외품목', name: '아이스 리드', min_qty: '80%', stock: 0 },
  { category: '이외품목', name: '핫 리드', min_qty: '1/4', stock: 0 },
  { category: '이외품목', name: '아이스 홀더', min_qty: '1/4', stock: 0 },
  { category: '이외품목', name: '핫 홀더', min_qty: '1/4', stock: 0 },
  // 베이커리
  { category: '베이커리', name: '커스터드 크로칸슈', min_qty: '5pack', stock: 0 },
  { category: '베이커리', name: '저당 크로칸슈', min_qty: '4pack', stock: 0 },
  { category: '베이커리', name: '우유 쿠키슈', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '커스터드 쿠키슈', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '초코 쿠키슈', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '치즈 쿠키슈', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '소금빵', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '아몬드 크루아상', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '소금식빵', min_qty: '2box', stock: 0 },
  { category: '베이커리', name: '초코 크루아상', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '말차 식빵', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '소시지 크루아상', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '모찌 식빵', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '화이트 청크', min_qty: '절반', stock: 0 },
  { category: '베이커리', name: '크런키 청크', min_qty: '절반', stock: 0 },
  { category: '베이커리', name: '더블초코 청크', min_qty: '절반', stock: 0 },
  { category: '베이커리', name: '우유 도넛', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '바닐라 도넛', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '팥 도넛', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '피스타치오 도넛', min_qty: '절반', stock: 0 },
  { category: '베이커리', name: '일반 핫도그', min_qty: '3pack', stock: 0 },
  { category: '베이커리', name: '마라 핫도그', min_qty: '3pack', stock: 0 },
  { category: '베이커리', name: '호두과자', min_qty: '1봉지', stock: 0 },
  { category: '베이커리', name: '우유 깨찰빵', min_qty: '절반', stock: 0 },
  { category: '베이커리', name: '옥수수빵', min_qty: '절반', stock: 0 },
  { category: '베이커리', name: '커스터드 깨찰빵', min_qty: '절반', stock: 0 },
  { category: '베이커리', name: '두쫀쿠', min_qty: '1박스', stock: 0 },
  { category: '베이커리', name: '로투스 두쫀쿠', min_qty: '1박스', stock: 0 },
  { category: '베이커리', name: '프랜치 갈릭 브레드', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '링고파이', min_qty: '1box', stock: 0 },
  { category: '베이커리', name: '플레인 베이글', min_qty: '2봉지', stock: 0 },
  { category: '베이커리', name: '치즈 베이글', min_qty: '1봉지', stock: 0 },
  { category: '베이커리', name: '무화과 베이글', min_qty: '1봉지', stock: 0 },
  // 오믈렛및마카롱
  { category: '오믈렛및마카롱', name: '우유 오믈렛', min_qty: '4box', stock: 0 },
  { category: '오믈렛및마카롱', name: '커스터드 오믈렛', min_qty: '4box', stock: 0 },
  { category: '오믈렛및마카롱', name: '녹차 오믈렛', min_qty: '4box', stock: 0 },
  { category: '오믈렛및마카롱', name: '초코 오믈렛', min_qty: '4box', stock: 0 },
  { category: '오믈렛및마카롱', name: '딸기 마카롱', min_qty: '절반', stock: 0 },
  { category: '오믈렛및마카롱', name: '초코 마카롱', min_qty: '절반', stock: 0 },
  { category: '오믈렛및마카롱', name: '오레오 마카롱', min_qty: '절반', stock: 0 },
  { category: '오믈렛및마카롱', name: '황치즈 마카롱', min_qty: '절반', stock: 0 },
  { category: '오믈렛및마카롱', name: '요거트 마카롱', min_qty: '절반', stock: 0 },
  { category: '오믈렛및마카롱', name: '얼그레이 마카롱', min_qty: '절반', stock: 0 },
  { category: '오믈렛및마카롱', name: '말차 마카롱', min_qty: '절반', stock: 0 },
  // 도쿄롤
  { category: '도쿄롤', name: '오리지널', min_qty: '절반', stock: 0 },
  { category: '도쿄롤', name: '초코', min_qty: '절반', stock: 0 },
  { category: '도쿄롤', name: '망고', min_qty: '절반', stock: 0 },
  { category: '도쿄롤', name: '떡볶이', min_qty: '절반', stock: 0 },
  { category: '도쿄롤', name: '고구마', min_qty: '절반', stock: 0 },
  { category: '도쿄롤', name: '녹차', min_qty: '절반', stock: 0 },
  { category: '도쿄롤', name: '피스타치오', min_qty: '절반', stock: 0 },
  { category: '도쿄롤', name: '저당', min_qty: '절반', stock: 0 },
  // 케익
  { category: '케익', name: '순수 우유', min_qty: '절반', stock: 0, expiry_date: '260801' },
  { category: '케익', name: '고구마', min_qty: '절반', stock: 0, expiry_date: '260524' },
  { category: '케익', name: '당근', min_qty: '절반', stock: 0, expiry_date: '260822' },
  { category: '케익', name: '당충전', min_qty: '절반', stock: 0, expiry_date: '260718' },
  { category: '케익', name: '티라미수 크레이프', min_qty: '절반', stock: 0, expiry_date: '260729' },
  { category: '케익', name: '초코 크레이프', min_qty: '절반', stock: 0, expiry_date: '260715' },
  { category: '케익', name: '커스터드 크레이프', min_qty: '절반', stock: 0, expiry_date: '260716' },
  { category: '케익', name: '밤', min_qty: '5', stock: 0, expiry_date: '260413' },
  { category: '케익', name: '우유 홀케익', min_qty: '3', stock: 0, expiry_date: '260628' },
  { category: '케익', name: '레드벨벳 홀케익', min_qty: '2', stock: 0, expiry_date: '260601' },
  { category: '케익', name: '당근 홀케익', min_qty: '1', stock: 0, expiry_date: '260704' },
  { category: '케익', name: '초코 크레이프 홀케익', min_qty: '1', stock: 0, expiry_date: '260527' },
  { category: '케익', name: '커스터드 홀케익', min_qty: '1', stock: 0, expiry_date: '260727' },
  { category: '케익', name: '두바이', min_qty: '절반', stock: 0, expiry_date: '260808' },
  { category: '케익', name: '저당 바스크 케익', min_qty: '3', stock: 0, expiry_date: '260718' },
  { category: '케익', name: '떠먹는 티라미수', min_qty: '3', stock: 0, expiry_date: '260711' },
  { category: '케익', name: '저당 티라미수', min_qty: '3', stock: 0, expiry_date: '260614' },
  { category: '케익', name: '파베 초콜릿', min_qty: '3', stock: 0, expiry_date: '261117' },
];
